tosca_definitions_version: cloudify_dsl_1_3

description: Install Kubernetes on kube-master and kube-node.

imports:
  - plugin:cloudify-ansible-plugin

inputs:

  playbook_path:
    type: string
    default: kubeadm-ansible/site.yaml

node_templates:

  kube-base-config-step1:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        configure:
          implementation: ansible.cloudify_ansible.tasks.run
          inputs:
            site_yaml_path: { get_input: playbook_path }
            run_data:
              network: flannel
              enable_dashboard: false
              master_ip: { get_attribute: [ kube-master, ip ] }
              network_interface: eth0
    relationships:
      - type: cloudify.ansible.relationships.connected_to_host
        target: kube-master
      - type: cloudify.ansible.relationships.connected_to_host
        target: kube-node

  kube-base-config-step2:
    type: cloudify.nodes.Root
    relationships:
      - type: cloudify.relationships.depends_on
        target: kube-base-config-step1

groups:

  master:
    members:
      - kube-master

  node:
    members:
      - kube-node

  kube-cluster:
    members:
      - master
      - node
