tosca_definitions_version: cloudify_dsl_1_3

description: >
  This blueprint creates infrastructure on AWS using Terraform.

imports:
  - http://cloudify.co/spec/cloudify/5.0.0/types.yaml
  - plugin:cloudify-terraform-plugin

inputs:

  agent_user:
    description: >
      The username of the agent running on the instance created from the image.
    default: 'centos'

node_templates:
  cloud_resources:
    type: cloudify.nodes.terraform.Module
    properties:
      executable_path: { get_secret: terraform_executable }
      plugins_dir: { get_secret: terraform_plugins_dir }
      storage_path: { get_secret: terraform_storage_path }
      resource_config:
        environment_variables:
          AWS_ACCESS_KEY_ID: { get_secret: aws_access_key_id }
          AWS_SECRET_ACCESS_KEY: { get_secret: aws_secret_access_key }
          AWS_DEFAULT_REGION: { get_secret: aws_region_name }
        variables:
          aws_region: { get_secret: aws_region_name }
          admin_user: { get_input: agent_user }
          admin_key_public: { get_secret: agent_key_public }
        source: resources/terraform/template.zip

capabilities:

  endpoint:
    description: The external endpoint of the application.
    value: { get_attribute: [ cloud_resources, resources, eip, instances, 0, attributes, public_ip ] }

  user:
    description: user ID.
    value: { get_input: agent_user }

  key_filename:
    description: Private agent key
    value: { get_secret: agent_key_private }
